// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Account struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Orders []*Order `json:"orders"`
}

type AccountInput struct {
	Name string `json:"name"`
}

type Catalog struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type CatalogInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type Mutation struct {
}

type Order struct {
	ID         string            `json:"id"`
	AccountID  string            `json:"accountId"`
	CreatedAt  time.Time         `json:"createdAt"`
	TotalPrice float64           `json:"totalPrice"`
	Products   []*OrderedProduct `json:"products"`
}

type OrderInput struct {
	AccountID string                 `json:"accountId"`
	Products  []*OrderedProductInput `json:"products"`
}

type OrderedProduct struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Quantity    int32   `json:"quantity"`
}

type OrderedProductInput struct {
	ID       string `json:"id"`
	Quantity int32  `json:"quantity"`
}

type PaginationInput struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type Query struct {
}
